[package]
name = "lace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lace-lexer = { version = "0.1.0", path = "./lexer" }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "lexer_bench"
harness = false

[workspace]
members = [
    "lexer",
    "parser",
]
