[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
lace-lexer = { path = "../lexer" }
lace-parser = { path = "../parser" }
lace-eval = { path = "../eval" }
byteorder = "1.5.0"
num-traits = "0.2.19"
num-derive = "0.4.2"
